# Generated by Django 3.0.3 on 2020-02-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Codigo_Propio', models.CharField(max_length=30)),
                ('Codigo_de_barras', models.CharField(max_length=30)),
                ('Factura_asociada', models.CharField(max_length=30)),
                ('Maquinaria', models.CharField(max_length=30)),
                ('Clasificacion', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='SELECCIONE', max_length=15)),
                ('Cantidad_de_producto', models.CharField(max_length=5)),
                ('Cantidad_de_subproducto', models.CharField(max_length=5)),
            ],
        ),
    ]
