# Generated by Django 3.0.3 on 2020-02-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Clasificacion',
            field=models.CharField(choices=[('SR', 'Freshman'), ('XS', 'Sophomore'), ('NP', 'Junior'), ('OD', 'Senior'), ('NOW', 'Graduate')], default='SELECCIONE', max_length=15),
        ),
    ]
