# Generated by Django 3.0.3 on 2020-02-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_auto_20200206_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Clasificacion',
            field=models.CharField(choices=[('Filtro\n', 'Filtro\n'), ('Aceite\n', 'Aceite\n'), ('Combustible\n', 'Combustible\n'), ('Correa\n', 'Correa\n'), ('Rodamientos\n', 'Rodamientos\n'), ('Repuestos', 'Repuestos')], default='SELECCIONE', max_length=15),
        ),
    ]
