# Generated by Django 3.0.3 on 2020-02-06 23:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_auto_20200206_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Maquinaria',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('6400', '6400'), ('6405', '6405'), ('6145J', '6145J'), ('6175M', '6175M'), ('6195M', '6195M'), ('6125D', '6125D'), ('6603', '6603'), ('6175M', '6175M'), ('6195M', '6195M')], max_length=100),
        ),
    ]
