# Generated by Django 3.0.3 on 2020-02-07 00:26

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_auto_20200206_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Cantidad_de_subproducto',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Codigo_Propio',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Codigo_de_barras',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Factura_asociada',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Maquinaria',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6400', '6400'), ('6405', '6405'), ('6145J', '6145J'), ('6175M', '6175M'), ('6195M', '6195M'), ('6125D', '6125D'), ('6603', '6603'), ('6175M', '6175M'), ('6195M', '6195M')], max_length=100),
        ),
    ]
