# Generated by Django 3.0.3 on 2020-02-07 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_auto_20200206_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
