# Generated by Django 3.0.3 on 2020-02-07 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_auto_20200206_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='Nombre',
        ),
    ]
