# Generated by Django 3.0.3 on 2020-02-10 22:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_auto_20200206_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_de_compra',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 2, 10, 22, 36, 18, 443572, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 2, 10, 22, 36, 30, 44325, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
