# Generated by Django 3.0.3 on 2020-02-13 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0011_auto_20200210_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clasificacion', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='Nombre',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='SubUbicacion',
            field=models.CharField(blank=True, choices=[('Caja 1', 'Caja 1'), ('Caja 2', 'Caja 2'), ('Caja 3', 'Caja 3'), ('Caja 4', 'Caja 4'), ('Caja 5', 'Caja 5'), ('Caja 6', 'Caja 6'), ('Caja 7', 'Caja 7'), ('Caja 8', 'Caja 8'), ('Caja 9', 'Caja 9'), ('Caja 10', 'Caja 10'), ('Caja 11', 'Caja 11'), ('Caja 12', 'Caja 12'), ('Caja 13', 'Caja 13'), ('Caja 14', 'Caja 14'), ('Caja 15', 'Caja 15')], default='NINGUNA', max_length=7),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Ubicacion',
            field=models.CharField(blank=True, choices=[('Bodega 1', 'Bodega 1'), ('Bodega 2', 'Bodega 2')], default='NINGUNA', max_length=8),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_de_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Compra(MM/DD/AAAA)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.Clasificaciones'),
        ),
    ]
