# Generated by Django 3.0.3 on 2020-02-14 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0012_auto_20200213_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinarias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maquinaria', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SubUbicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubUbicacion', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ubicacion', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='Maquinaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.Maquinarias'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='SubUbicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.SubUbicaciones'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.Ubicaciones'),
        ),
    ]
