# Generated by Django 3.0.3 on 2020-02-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0013_auto_20200213_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Maquinaria',
        ),
        migrations.AddField(
            model_name='producto',
            name='Maquinaria',
            field=models.ManyToManyField(blank=True, null=True, to='djangoapp.Maquinarias'),
        ),
    ]
