# Generated by Django 3.0.3 on 2020-02-17 21:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0016_auto_20200214_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Maquinaria',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('aaaaaa', 'aaaaaa'), ('aaaasddd', 'aaaasddd'), ('d2d2d2d2d2', 'd2d2d2d2d2'), ('dddddfggggg', 'dddddfggggg')], max_length=100),
        ),
    ]
