# Generated by Django 3.0.3 on 2020-02-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0017_auto_20200217_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='exportar',
            field=models.BooleanField(default=False),
        ),
    ]
