# Generated by Django 3.0.3 on 2020-02-18 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0019_producto_ubicacion_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Ubicacion_search',
        ),
    ]
