# Generated by Django 3.0.3 on 2020-02-24 07:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0020_remove_producto_ubicacion_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Maquinaria',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('6125D', '6125D'), ('SEMBRADORA', 'SEMBRADORA'), ('RASTRA 22 DISCOS', 'RASTRA 22 DISCOS'), ('6400', '6400'), ('7200', '7200'), ('1450', '1450'), ('CINCEL', 'CINCEL'), ('RASTRA', 'RASTRA'), ('PICHON', 'PICHON'), ('955', '955'), ('6195M', '6195M'), ('6145J', '6145J'), ('LUV', 'LUV'), ('6175M', '6175M'), ('6603', '6603'), ('MAHINDRA', 'MAHINDRA'), ('5400', '5400'), ('ARADO KUHN', 'ARADO KUHN'), ('KUBOTA', 'KUBOTA'), ('KUBOTA', 'KUBOTA'), ('5600', '5600'), ('6405', '6405'), ('2850', '2850'), ('RASTRA 22DISCOS', 'RASTRA 22DISCOS'), ('NISSAN', 'NISSAN')], max_length=100),
        ),
    ]
