# Generated by Django 3.0.3 on 2020-02-24 18:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0021_auto_20200224_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Maquinaria',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(12, '6125D'), (13, 'SEMBRADORA'), (14, 'RASTRA 22 DISCOS'), (15, '6400'), (16, '7200'), (18, 'CINCEL'), (19, 'RASTRA'), (20, 'PICHON'), (21, '955'), (22, '6195M'), (23, '6145J'), (24, 'LUV'), (25, '6175M'), (26, '6603'), (27, 'MAHINDRA'), (28, '5400'), (29, 'ARADO KUHN'), (30, 'KUBOTA'), (31, 'KUBOTA'), (32, '5600'), (33, '6405'), (34, '2850'), (35, 'RASTRA 22DISCOS'), (36, 'NISSAN'), (37, '1450')], max_length=100),
        ),
    ]
